version: ~> 1.0

import:
  - silverstripe/silverstripe-travis-shared:config/provision/self-jobs-range.yml

env:
  global:
    - REQUIRE_EXTRA="silverstripe/gridfieldqueuedexport:^2 symbiote/silverstripe-queuedjobs:^4"
    - PHPUNIT_SUITE="recipe-form-building"
